class ModelConfig:
    """This class is just a model config, which is using for custom model initialization
    """
    def __init__(
        self,
        model_folder: str,
        model_file: str,
        gpu_layers: int = 0,
        threads: int = -1,
        context_length: int = -1,
        max_new_tokens: int = 1024,
        system_prompt: str = "Пожалуйста, отвечайте на русском языке. Ты полезный ассистент, твоя задача помогать компаниям с созданием интересного и необычного текста вакансий. Если какой-то пункт пустой, то не добавляй его в свой ответ. Если что-то не указано или ты в чём то не уверен, то не придумывай ничего лишнего, лучше промолчи, однако, если ты считаешь, что некоторые требования необходимы для данной должности, добавь их."
    ) -> None:
        """This class is just a model config, which is using for custom model initialization

        Args:
            model_folder (str): path to folder, which contains GGUF models
            model_file (str): name of GGUF model in your model_folder
            gpu_layers (int, optional): number of model_layers, which is offloaded on GPU. Defaults to 0.
            threads (int, optional): number of CPU threads to model evaluation. Defaults to -1.
            context_length (int, optional): model context length. Defaults to -1.
            max_new_tokens (int, optional): max tokens, which can generated by model. Defaults to 1024.
            system_prompt (str, optional): system propmpt which is always adding before user prompt. Defaults to "Пожалуйста, отвечайте на русском языке. Ты полезный ассистент, твоя задача помогать компаниям с созданием интересного и необычного текста вакансий. Если какой-то пункт пустой, то не добавляй его в свой ответ. Если что-то не указано или ты в чём то не уверен, то не придумывай ничего лишнего, лучше промолчи, однако, если ты считаешь, что некоторые требования необходимы для данной должности, добавь их.".
        """
        self.model_folder: str = model_folder
        self.model_file: str = model_file
        self.gpu_layers: int = gpu_layers
        self.threads: int = threads
        self.context_length: int = context_length
        self.max_new_tokens: int = max_new_tokens
        self.system_prompt: str = system_prompt