import os
from typing import List

from model_config import ModelConfig
from ctransformers import AutoModelForCausalLM

class Model:
    """Model class for Saiga-Mistral models
    """
    def __init__(self, model_config: ModelConfig) -> None:
        """Init Saiga-Mistral model

        Args:
            model_config (ModelConfig): config for model initialization, more information in ModelConfig class
        """
        model_path = os.path.join(model_config.model_folder, model_config.model_file)
        
        self._model = AutoModelForCausalLM.from_pretrained(
            model_path,
            gpu_layers=model_config.gpu_layers,
            context_length=model_config.context_length,
            max_new_tokens=model_config.max_new_tokens,
            threads=model_config.threads
        )
        self._system_prompt = model_config.system_prompt
        
    def _create_prompt(self, request: str) -> str:
        """This function create correctly prompt based on model
        system prompt and user request

        Args:
            request (str): user request to the model

        Returns:
            str: correctly prompt which can be transmitted to the model
        """
        prompt: str = f'''<|im_start|>system
{self._system_prompt}<|im_end|>
<|im_start|>user
{request}<|im_end|>
<|im_start|>assistant'''

        return prompt
    
    def _get_request(
        self,
        vacancy_name: str,
        company_name: str = "",
        company_place: str = "",
        schedule: str = "",
        experience: str = "",
        key_skills: List[str]=[],
    ) -> str:
        """This function preprocess the user's request

        Args:
            vacancy_name (str): Vacancy name
            company_name (str, optional): Company name. Defaults to "".
            company_place (str, optional): Comany place (vacancy place). Defaults to "".
            schedule (str, optional): Vacancy schedule. Defaults to "".
            experience (str, optional): Vacancy experience. Defaults to "".
            key_skills (List[str], optional): List of key skills for this vacancy. Defaults to [].

        Returns:
            str: return user request based on user form from web client
        """
        capitalize_skills: List[str] = [f"'{skill.capitalize()}'" for skill in key_skills]
        
        request: str = (f'Напиши текст вакансии для должности "{vacancy_name}". Название компании: "{company_name}". ',
                   f'Расположение: {company_place}. График работы: {schedule}. Опыт работы: {experience}. ',
                   f'Ключевые навыки: {", ".join(capitalize_skills)}') # type: ignore
        return request

    def generate(
        self,
        vacancy_name: str,
        company_name: str = "",
        company_place: str = "",
        schedule: str = "",
        experience: str = "",
        key_skills: List[str]=[],
    ) -> str:
        """This function pass correct prompt to the model and return model result.

        Args:
            vacancy_name (str): Vacancy name
            company_name (str, optional): Company name. Defaults to "".
            company_place (str, optional): Comany place (vacancy place). Defaults to "".
            schedule (str, optional): Vacancy schedule. Defaults to "".
            experience (str, optional): Vacancy experience. Defaults to "".
            key_skills (List[str], optional): List of key skills for this vacancy. Defaults to [].

        Raises:
            RuntimeError: this exception is raising when unexpected generation error occured

        Returns:
            str: vacancy text generated by LLM
        """
        
        request: str = self._get_request(
            vacancy_name,
            company_name,
            company_place,
            schedule,
            experience,
            key_skills,
        )
        
        prompt: str = self._create_prompt(request=request)
        
        outputs: str = ""
        
        try:
            outputs: str = self._model(prompt) # type: ignore
        except:
            raise RuntimeError("Unexpected model generation error")

        while '<|im_end|>' in outputs:
            outputs = outputs.replace('<|im_end|>', '')
        while '<|im_start|>' in outputs:
            outputs = outputs.replace('<|im_start|>', '')
        while ';' in outputs:
            outputs = outputs.replace(';', '\n')
        return outputs