from typing import List
from pydantic import BaseModel, Field

class RequestGenerateVacancy(BaseModel):
    """Class for form request validation to create new generation task

    Args:
        BaseModel (_type_): default pydantic basemodel
    """
    vacancy_name: str = Field(alias='vacancyName')
    company_name: str = Field(alias='companyName', default="")
    company_place: str = Field(alias='companyPlace', default="")
    schedule: str = ""
    experience: str = ""
    key_skills: List[str] = Field(alias='keySkills', default=[])
    token: str
    
class RequestUserConnect(BaseModel):
    """Class for check-answer request validation to check current task status

    Args:
        BaseModel (_type_): default pydantic basemodel
    """
    token: str
    
class ModelConfig(BaseModel):
    """This class is just a model config, which is using for custom model initialization

    Args:
        BaseModel (_type_): default pydantic basemodel
    
    Fields:
        model_folder (str): path to folder, which contains GGUF models
        model_file (str): name of GGUF model in your model_folder
        gpu_layers (int, optional): number of model_layers, which is offloaded on GPU. Defaults to 0.
        threads (int, optional): number of CPU threads to model evaluation. Defaults to -1.
        context_length (int, optional): model context length. Defaults to -1.
        max_new_tokens (int, optional): max tokens, which can generated by model. Defaults to 1024.
        system_prompt (str, optional): system propmpt which is always adding before user prompt. Defaults to "Пожалуйста, отвечайте на русском языке. Ты полезный ассистент, твоя задача помогать компаниям с созданием интересного и необычного текста вакансий. Если какой-то пункт пустой, то не добавляй его в свой ответ. Если что-то не указано или ты в чём то не уверен, то не придумывай ничего лишнего, лучше промолчи, однако, если ты считаешь, что некоторые требования необходимы для данной должности, добавь их.".
        
    """
    folder_name: str = Field(alias='folderName')
    file_name: str = Field(alias='fileName')
    gpu_layers: int = Field(alias='companyPlace', default=0)
    threads: int = -1
    context_length: int = Field(alias='contextLength', default=-1)
    max_new_tokens: int = Field(alias='maxNewTokens', default=1024)
    system_prompt: str = Field(alias='systemPrompt', default="Пожалуйста, отвечайте на русском языке. Ты полезный ассистент, твоя задача помогать компаниям с созданием интересного и необычного текста вакансий. Если какой-то пункт пустой, то не добавляй его в свой ответ. Если что-то не указано или ты в чём то не уверен, то не придумывай ничего лишнего, лучше промолчи, однако, если ты считаешь, что некоторые требования необходимы для данной должности, добавь их.")
